version: '3.8'
services:
  sharc_react_prod:
    container_name: sharc_react_prod
    # stdin_open: true
    # tty: true
    build:
      context: ../
      dockerfile: docker/Dockerfile.prod
    ports:
      - "8080:80"
    # env_file:
    #   - ./.env