version: '3.8'
services:
  sharc_react_dev:
    container_name: sharc_react_dev
    build:
      context: ../
      dockerfile: docker/Dockerfile.dev
    image: sharc_react_dev_image
    ports:
      - "3000:3000"
    volumes:
      - ../src:/usr/src/app/frontend/src:ro
    env_file:
      - .env