# Development stage:
# building the files into static form

FROM node:18.18.2-alpine as build

WORKDIR /usr/src/app/frontend

COPY package*.json .

RUN npm install

COPY . .

RUN npm run build

# Production stage
# serving static files to web via NGiNX server

FROM nginx:1.9.15-alpine

COPY --from=build /usr/src/app/frontend/build /usr/share/nginx/html