version: '3.8'
services:
  sharc_react:
    # stdin_open: true
    # tty: true
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./src:/usr/src/app/frontend/src:ro
    env_file:
      - ./.env