version: '3.8'
services:
  postgres-db:
    image: postgres:16.0-alpine
    container_name: postgres-db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres-db
    ports:
      - "5434:5434"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-container
    environment:
      PGADMIN_DEFAULT_EMAIL: robot.sharc@gmail.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:5050"