version: '3.8'

services:
  sharc_back_dev:
    container_name: sharc_back_dev
    build:
      context: ../
      dockerfile: docker/Dockerfile.dev
      target: development
    image: sharc_back_dev_image
    volumes:
      - ../:/usr/src/app/backend
      - /usr/src/app/node_modules
      - ../../assets:/usr/src/app/assets
    ports:
      - 3001:3001
    command: npm run dev
